services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TRAW\LuxletterReceiverImport\:
      resource: '../Classes/*'

  TRAW\LuxletterReceiverImport\Controller\ReceiverimportController:
    public: true
